# Generated by Django 5.2.17 on 2026-08-31 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('faixa_etaria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFinalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outro_descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('finalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.finalidade')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.pessoa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pessoa', 'finalidade'), name='pessoa_finalidade_unica')],
            },
        ),
    ]
